#!/bin/bash

force=false

# Check for --force option
while [ "$#" -gt 0 ]; do
    case "$1" in
        --force )
            force=true
            shift
            ;;
        * )
            break
            ;;
    esac
done


sudo timedatectl set-timezone America/New_York

# __TODO__ clarify fzf: we also have it in vim through plug installer
# __TODO__ clarify fzf: additional lines are required in ~/.bashrc to activate the Ctrl-R Ctrl-T and Alt-C key bindings. **<TAB> cmopletion still does not work
sudo apt-get install fzf

#if [ "$force" = true ]; then
#    echo "Force option detected. Proceeding..."
#else
#    read -p "Are you certain? Type 'yes-i-am-certain': " response
#fi

#if [ "$response" = "yes-i-am-certain" ] || [ "$force" = true ]; then
#       echo ">>> swapoff for k8s in general"
#else
#    echo "Skipping execution. Make sure to type 'yes-i-am-certain' to proceed or use --force"
#    exit 1
#fi
